### ISSUE TITLE
Evo not appearing in mp missions list(Altis0

### ISSUE THREAD

**Issue by Call-911** [Kolmain/Evolution-A3#12]
I downloaded the file from this site to take a look an see how you were coming along on this as well this has been my most anticipated mission to see make it's way to ArmA3. Anyways i downloaded the file an added it to my document/arma3 other profiles/mpmissions an to be safe added it to my root arma3 mission folder as well to be safe. So far it does'nt appear in the mission list under Altis when trying to host an test online. Not sure if maybe it's me or maybe i'll wait til u get a more finalised version ready for testing.

**Comment by Kolmain** [comment]
Thanks Call-911,

It's probably the name of the folder. Change it to 

```
evolution-a3.Altis
```

and it should work!

**Comment by Kolmain** [comment]
See here:
https://github.com/Kolmain/Evolution-A3/releases/tag/DEV1
