### ISSUE TITLE
Virtual Arsenal Clientside Whitelisting

### ISSUE THREAD

**Issue by Kolmain** [Kolmain/Evolution-A3#2]
VA needs to be whitelisted according to player rank.

**Comment by Kolmain** [comment]
According to (http://forums.bistudio.com/showthread.php?190967-Removing-items-from-arsenal&p=2922591&viewfull=1#post2922591) you don't have to initiate the VA before adding items, it does it automatically.

**Comment by Kolmain** [comment]
Raised question on BIF.
http://forums.bistudio.com/showthread.php?191311-Progression-of-Arsenal-Whitelist

**Comment by kmain4** [comment]
This should be resolved, needs testing in master branch.
