### ISSUE TITLE
New Compositions FARP/MASH

### ISSUE THREAD

**Issue by Kolmain** [Kolmain/Evolution-A3#21]
Build new compositions for FARPs/MASHs

**Comment by Call-911** [comment]
Nice :D

**Comment by Call-911** [comment]
Looking forward to it can't remember what the class name is for the small 3 side bunkers that were used in ArmA2. players could cycle between 3-4 differnt types of bunkers but not sure if thats good idea, maybe just 1 for personal defense or maybe add it to the commander slot to place the enclosed/w roof bunker an maybe encourage teamplay.

**Comment by Kolmain** [comment]
FARPs/MASHs will work the same way they did in EvoBlue. I think you're talking about #20 , and for that I'm going to make some kind of foxhole-dig in action. Bunker placing will be handled by R3F and later the Commander through Zeus.
