### ISSUE TITLE
FARP/MASH Space Check

### ISSUE THREAD

**Issue by Kolmain** [Kolmain/Evolution-A3#24]
Check needs to be put in place to verify there is enough room for FARP/MASH.

**Comment by kmain4** [comment]
Should be implemented in master branch. Needs testing.

**Comment by kmain4** [comment]
http://images.akamai.steamusercontent.com/ugc/540772837775781145/AAABBC201AD3AD0E13885D38D180AFACECFB752D/

**Comment by Call-911** [comment]
Same thing happens when placing a Farp down. Maybe theres a way to cplace a check trigger/script for placement like the one does for the MHQ Hemmett.
