### ISSUE TITLE
Orcas don't return after paradrop

### ISSUE THREAD

**Issue by kmain4** [Kolmain/Evolution-A3#28]
http://images.akamai.steamusercontent.com/ugc/540772837775658061/9BFC0C6448D98DB53BBF168F37B949030219A27C/

Orcas stay over AO and HQ after they paradrop units.

Reported here: http://forums.bistudio.com/showthread.php?191210-CO30-Evolution-A3-(Sahrani)-WIP&p=2928932&viewfull=1#post2928932

**Comment by kmain4** [comment]
I suspect its an issue with using `doMove` instead of waypoints.

**Comment by Call-911** [comment]
I did notice one Orca come in an drop off the paras an than fly away but b4
that there was still the one than was just hovering over the town.

**Comment by kmain4** [comment]
commit 197f3f5 should resolve.

**Comment by Call-911** [comment]
Will keep an eye on em today.

**Comment by kmain4** [comment]
I'll post the fix in the hotfix to be released tonight.

**Comment by kmain4** [comment]
@Call-911 can you confirm this is fixed?

**Comment by Call-911** [comment]
Yeah just got home from road trip, will take a look after bit. other nite i
shot the tail rotor out of the one hoverin over 1st town an an hr later he
acted like he was still trying to track me. Will check in a bit.

**Comment by Kolmain** [comment]
Okay, let me know!

**Comment by Call-911** [comment]
Just tested it believe I have the latest RC2 an the reinforcement heli was
still there(shot 1 down with tank). Gonna get my server back probably
tomorow so will load it up on there too to test, less u think it's not
ready for some reason. be nice to test with a couple more players (less u
don't want it to be played on open pub server yet) or I can pw the
server---just a thought.

**Comment by Kolmain** [comment]
I'm working on getting my dedi online tonight, I don't mind but I know its not playable yet. I'm working on getting it to that point tonight, standby for RC3!

**Comment by Kolmain** [comment]
fixed in next update
