### ISSUE TITLE
Loadout Saved After Modified by ATM_Airdrop

### ISSUE THREAD

**Issue by kmain4** [Kolmain/Evolution-A3#33]
When you insert via HALO drop, you leave the base and trigger the loadout saving. Before the script captures your loadout, ATM_airdrop changes it.

**Comment by kmain4** [comment]
committ 4eca5a1 _should_ resolve this.

**Comment by Call-911** [comment]
Yeah was just a pain respawning with the parachute :D Gonna test the version you posted in the forumns about earlier. Must apoligise the excitment somtimes gets the better of me when posting feedback etc. Just happy to see Evo in ArmA3 somthing the game has been missing IMO.

**Comment by kmain4** [comment]
No problem. The version on the forum will have the same issue. This will be fixed in tonight's hotfix, or if you understand how to edit files you can add commit 4eca5a1.

**Comment by Call-911** [comment]
Yeah will just wait for your fix. Played a lil bit earlier could'nt find VA again even after respawning so will wait til tomorrow an check latest.
