### ISSUE TITLE
Server Lag Every 2-3 Seconds

### ISSUE THREAD

**Issue by Lampelampelampe** [Kolmain/Evolution-A3#40]
Hi, first of all i would like to realy thank you for creating this mission!!!

Ive been playing the previous version and it was running ok, now installed the updated version and 
since that the mission is "jerking" (i hope this is the right word :) )
In general it is like: we are starting the mission and immediatly its starting to jerking. We can walk / run or do what so ever, every 2-3-4 seconds its the game stands still for about 1 second. Its feeling like its loading something... 

Can you pls let me know which details you need to find this error?

brgds
Lampelampelampe

**Comment by Kolmain** [comment]
Thanks for submitting a ticket and your support, @Lampelampelampe .

I'll look into this tomorrow, but I tried to reproduce it and couldn't on my dedicated server. What are your server specs and have you tried any other missions? Does it happen only in the base or in the field? Are you using any mods?

**Comment by Lampelampelampe** [comment]
Server spec i need to ask the provider.
We are not using any mods.
Its happening from start at the base and continues all the time. At Base, in Field, at Town etc...
I was running couple of missions now and this is happening only with this mission.

**Comment by Kolmain** [comment]
Is it public? Can I join and test it?

**Comment by Lampelampelampe** [comment]
ah yes, can i add you on steam?

**Comment by Kolmain** [comment]
Yeah, add me on steam.

**Comment by Lampelampelampe** [comment]
or maybe you come to our teamspeak?

ts.schwarzelegion.de

**Comment by Lampelampelampe** [comment]
i think i added you on steam :)

Server is not public, but i can give you password to join. 

Have just loaded the mission again.

**Comment by Lampelampelampe** [comment]
hmm.... ok, we have 2 persons with this problem. Now another one joint and he dont have this problem at all.. testing some things now and revert as soon as ive found the problem!

**Comment by Kolmain** [comment]
I won't be available until tomorrow. Let me know what you find, thanks!

**Comment by Lampelampelampe** [comment]
no, unfo cant find the error. we tested it now with 6 persons. 2 have same problem but the others can play. reinstalled grafikdriver, made all cpu tweaks i found for arma 3 and all other tweaks, but its still like he is doing something every 2-3 seconds that freezes the game for abt 1 second. like he is loading something which is to much for cpu. im playing with i7 and nvidia 970. all other missions runs without any problems and even your former version with running with no problems... i disabled the weather script in the mission but even that doesnt help... i dont know what i can change to run the mission.

**Comment by Kolmain** [comment]
So the last version works? I'll start looking for differences between the two.

**Comment by Kolmain** [comment]
@Lampelampelampe can you try using a new user profile in ArmA3? Evo saves data to the user profile to use when you reconnect. Maybe theres something going on with yours...

**Comment by Lampelampelampe** [comment]
This i will try and let you know. Will be at Home only today evening but will give a reply asap.

Furthermore i tested the mission in Multiplayer on my on PC as server. When Mission is starting it takes about 1-2 Minutes until the mission as such is starting -> showing the base from the top with the screen Arma 3 Evolution and all the sounds etc... But within this 1-2 Minutes everything is running smooth, no lags etc.. But immy when the mission is starting, lags or jerking is starting.

Will try new user Profile and let you know!
+++

Btw: Now all my peoples playing the mission and complaining that the AI is in our base within 15-20 minutes already and they all getting shot while they are spawning :) Are you working on it?

**Comment by kmain4** [comment]
Yes, I'm aware and working on #39 .

**Comment by Kolmain** [comment]
Yes, I'm aware and working on #39 .

**Comment by Lampelampelampe** [comment]
... WORKED! :+1: 

Lagfree with new User Profile!!!
How can this be... i dont understand but im so glad that you could help me!!!

Keep Up your good work please!
+++

Question: What about the Jet flying around? He is respawning after you shot him down? Would it be possible to take over all Airfields to avoid that he is coming back?

**Comment by Lampelampelampe** [comment]
Weird, now i connected again and it starts to lagg again...
Now i turned off my antivirus... and he is not lagging anymore...
Maybe it was the antivirus (microsoft essentials) all the time and it needs a bit time to load?

**Comment by Kolmain** [comment]
I'll look into the OPFOR CAS.

As far as the reoccuring issue, if you A/V is causing it there isn't much I can do about it. The method I'm using stores your player info in your .arma3profile file, which might be causing the A/V to rescan it. If you can confirm that its microsoft essentials causing it I'll look into it.

**Comment by Lampelampelampe** [comment]
yes its is microsoft essentials. stupid thing is, that the previous version was running fine. there i dont had this problems. but with the new version i need to turn off the antivirus.

**Comment by kmain4** [comment]
Ill try and add a parameter that disables that feature.

**Comment by kmain4** [comment]
Committ 63c8686 should resolve this issue.
