### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Lampelampelampe** [Kolmain/Evolution-A3#41]
Hi, i think we found some bugs:

1.) We destroyed the radio tower, but Enemy still getting reinforcement with the Heli
2.) When my teammate reviving me, im lossing all my gear and spawning with the first gear i have chosen at start of the mission, but when im taking gear from enemy and somebody is reviving me, i keep that gear. If im not beeing revived but spawn normal, i have my normal gear. 
+++

If this is not the place to report bugs, pls let me know! :)

**Comment by Lampelampelampe** [comment]
Ok, just cleared our first city!

Heli was bringing reinforcement till the very end.

With the 3rd Rank we can use light tanks and other vehicels, but till the very end (rank major) we couldnt use the trucks for ammo/repair/refuel... this is not ok in my opinion. We should be able to load ammo and repair vehicels earlier. 

2 peoples from us had a bug: when they are zooming with a weapon (normal weapon and launcher), its going out of the zoom and shouldering the weapon and immy takes it back into the hand. Dont know whether its an Arma Bug or belongs to the mission.

**Comment by Kolmain** [comment]
Thanks for the reports @Lampelampelampe, try and make a different issue for each bug so I can keep track. I've fixed the nonstop heli, and hopefully the revive bug too, that was bothersome. I'll add the support assets to rank1 now, and I haven't seen anything like this weapon zoom. The next release will have a new parameter to disable persistence, which resets your position if you rejoin the game. Test with that setting DISABLED and we'll see what happens.
