### ISSUE TITLE
Loadout saves issue

### ISSUE THREAD

**Issue by Call-911** [Kolmain/Evolution-A3#54]
What you did: saved loadout via auto save an also in Virtual Arsenal.
What you expected to happen: to respawn at  my mash/base with complete loadout.
What actually happened:spawned with lost ammunition(grenades an GL for 203's.
Any errors/logs to help:not at this time will try an capture a screen shot of this today..

**Comment by Kolmain** [comment]
Perfect bug report, thank you! I'll get to work hunting this one down...

**Comment by Kolmain** [comment]
Fixed in 1.1.
