### ISSUE TITLE
Starting base turns into self exploding mess

### ISSUE THREAD

**Issue by alexcroox** [Kolmain/Evolution-A3#59]
Consistently after about 10minutes of gameplay the base starts self exploding, and it gets worse and worse over time. It looks to be vehicles spawning inside other vehicles. I'm not sure if people leaving vehicles in the field that de-spawn, re-spawn on top of a vehicle that's re-spawned there in the mean time. As you can imagine it's a bit of a deal breaker when your base is on fire every game and you're getting very low FPS as a result.

**Comment by alexcroox** [comment]
Another cause might be air vehicles shooting AGMs at people as they get in vehicles at base? Couldn't say that for sure but might be worth setting everyone to "captive" while inside the base area to stop air targets engaging from great distances while people are kitting up?

**Comment by Kolmain** [comment]
What version are you running? Thanks for the report, this should be resolved today/tomorrow in 1.1.
