### ISSUE TITLE
Starting balance issues

### ISSUE THREAD

**Issue by alexcroox** [Kolmain/Evolution-A3#60]
I'm not sure what the minimum player guidelines for this mission are, or if it adapts the resistance based on number of players but the starting 3 objects seem very OP against 5-10 players.

When you spawn in with no AA capability and nothing but a handful of starter weapons going up against a Kajman and several tanks always ends as badly as you'd imagine it to. Perhaps the difficulty should be ramped up as you move on?

We only just made it to the 2nd area of objectives after a long hard fight, the same 3 objectives were there (clear town, capture someone, blow a tower). Is it the same 3 across the entire map or does it vary?

**Comment by Kolmain** [comment]
The core objectives are always the same, Destroy the Tower, Clear the Town, optionally Capture the Officer. That's what Evolution is all about. The side missions are randomly generated. Again, what version is this?

**Comment by alexcroox** [comment]
I think we built from source last week, I'll give it another go with your work in #59 thank you!

**Comment by Kolmain** [comment]
The dev branch can be broken at any time. Master is always the latest stable version. Standby for incoming v1.1. The beta is available under releases.
