### ISSUE TITLE
No HALO drops

### ISSUE THREAD

**Issue by MaximusAttackAU** [Kolmain/Evolution-A3#66]
I have noticed that there are no HALO drops when you either start in easy mode or when you save a game in normal mode, exit then come back.
Forgive me if these are known issues.

PS: Not sure if this is an issue or a parameter at this stage but my vehicle disappeared after saving, exiting and then restarting?

**Comment by Kolmain** [comment]
This mission doesn't support saving and reloading. Are you talking about leaving and rejoining a server or saving in SP? This is a multiplayer only mission. If you'd like to play it alone, you have to host it in MP. @MaximusAttackAU

**Comment by MaximusAttackAU** [comment]
Ok, Thanks. I would love to host it sometime but worry that my internet connection might not be good enough. I'm going to have to give it a try though..
