### ISSUE TITLE
database

### ISSUE THREAD

**Issue by jus61** [Kolmain/Evolution-A3#67]
ould you let the run on a database

**Comment by Kolmain** [comment]
@jus61 I have no idea what this is.

**Comment by jus61** [comment]
https://github.com/Torndeco/extDB2

**Comment by jus61** [comment]
Sorry my Endlish

**Comment by Kolmain** [comment]
I'll look into this, thanks.

**Comment by xBloodshed** [comment]
+1 for this. It would be great
