### ISSUE TITLE
Error in expression ( 1.2 )

### ISSUE THREAD

**Issue by jus61** [Kolmain/Evolution-A3#68]
Error in expression <alues,_selectedValue];
_unsortedArray set [_selectedIndex,_removeElement];
_un>
Error position: <set [_selectedIndex,_removeElement];
_un>
Error Typ Jede, erwartet Zahl
File A3\functions_f\Arrays\fn_sortBy.sqf, line 135

**Comment by Kolmain** [comment]
Hi @jus61, please refer to "issue" #52 on "How to submit an issue". I appreciate the error log, but I have not idea where that's from or what you were trying to do. Thanks!

**Comment by jus61** [comment]
I have loaded the mission and wanted the server start!
Server starts but just get the error message

**Comment by Kolmain** [comment]
Okay, so upon starting the server that is the message you get, and the server DOES NOT load the mission?

**Comment by jus61** [comment]
YAS

**Comment by Kolmain** [comment]
Issue resolved in hotfix, get it @ https://github.com/Kolmain/Evolution-A3/releases

**Comment by jus61** [comment]
thx
