### ISSUE TITLE
Sahrani version on CUP ?

### ISSUE THREAD

**Issue by Vonrichter** [Kolmain/Evolution-A3#70]
Hello Kolmain,

I'm a member of OTEA'S Team (http://otea.forum-pro.fr/, a French sim team on arma 3) I've tried to launch the Sahrani version of Evolution and i've seen which mods are needed (Sahrani Rearmed, MAS etc...).
All In Arma is a discontinued project, where some dev have moved to CUP Project (http://cup-arma3.org/).
Is it planned to "migrate" to CUP? (replacing MAS and Sahrani Reamed weapons by CUP weapons, MAS vehicles by CUP vehicles etc...)
If not, could i try to migrate to CUP? (maybe a fork of the current sahrani version)

best Regards,

**Comment by Dumedo** [comment]
Great idea Vonrichter

**Comment by kmain4** [comment]
See Sahrani branch.

**Comment by Vonrichter** [comment]
Thanks for having moved Evo on CUP... Thank you very much :)

**Comment by Kolmain** [comment]
No problem!
