### ISSUE TITLE
Sarhani Branch - access denied to vehicles

### ISSUE THREAD

**Issue by Vonrichter** [Kolmain/Evolution-A3#71]
**What you did:** tried to get in vehicle in driver slot
**What you expected to happen:** taking a vehicle, according to my rank
**What actually happened:** accress denied, with a message that said "you are not qualified for this vehicle"
**Any errors/logs to help:** no error in rpt file.

The mission has been compiled this morning with the last version of the branch; options used when launching the mission were the default one.
The ranked weapons works very well, not vehicle. As a private i should have access to unarmed humvee; these reject me too with "you are not qualified" error.
When you begin to play there are only civilian cars to bring you to the first objective.

If i disable ranked vehicles, all vehicles are available.

**Comment by Kolmain** [comment]
Thanks, I needed somone to confirm this, going to work on it now.

**Comment by Vonrichter** [comment]
thank you very much. If you need some test on a dedicated sever, you can contact me :)

**Comment by Kolmain** [comment]
Fixed!
