### ISSUE TITLE
Sarhani Branch - No Pilot Slot

### ISSUE THREAD

**Issue by Vonrichter** [Kolmain/Evolution-A3#72]
Hello Kmain4,

As the title said; the Assign screen does not provide Pilot slots.

For the moment we have to disable "require Pilot Slot to Pilot".

**Comment by Kolmain** [comment]
Evo-A3 doesn't require you to be a pilot, it requires you to be in the pilot uniform. I haven't added those yet, but if you get into a chopper in the HQ, it should auto-swap your outfit.

**Comment by Vonrichter** [comment]
Understood. I will test and give you feedback :)

**Comment by Kolmain** [comment]
This was disabled by default per original Arma Evolution Blue.
