### ISSUE TITLE
Sarhani Branch - Mobile HQ?

### ISSUE THREAD

**Issue by Vonrichter** [Kolmain/Evolution-A3#73]
Hello Kmain4,

i've seen that Parameters screen provide a Mobile HQ. But there is no mobile HQ in the base when this parameter is activated.
Is it linked to sometyhing? Rank? Number of players?

**Comment by Kolmain** [comment]
I haven't finished moving that over. Sahrani is so small, I'm not sure if we should have a MHQ? The classic didnt!

**Comment by Vonrichter** [comment]
ah, understood...
I think we should have a MHQ, because Sarhani is not SO small, it is far bigger dans Stratis.

But consider this as NOT TOP PRIORITY. We can wait a decision for this (or a poll, maybe)

**Comment by Kolmain** [comment]
For now, I'm removing the MHQ. FARPs and MASHs act as respawn points, so that should be plenty!
