### ISSUE TITLE
Error at the map screen, before the complete loading and misplacement of markers

### ISSUE THREAD

**Issue by Vonrichter** [Kolmain/Evolution-A3#74]
What you did: i've selected a slot then i clicked on OK to load the mission
What you expected to happen: display the map then validate again to load the mission
What actually happened:  error "Script scripts\tpw_park.sqf not found"

Several screens show the initial error and the misplacement of markers.

![arma3 2016-05-02 18-43-38-669](https://cloud.githubusercontent.com/assets/16905993/14960620/cfe5c560-1095-11e6-99e2-cef17b14a594.png)
![arma3 2016-05-02 18-40-00-514](https://cloud.githubusercontent.com/assets/16905993/14960618/cfe0e928-1095-11e6-896f-a4e986dd45bf.png)
![arma3 2016-05-02 18-43-21-979](https://cloud.githubusercontent.com/assets/16905993/14960619/cfe1bb0a-1095-11e6-8073-b890b69888a2.png)

**Comment by Kolmain** [comment]
This looks like you built up the `master` branch instead of the `sahrani` branch. Please confirm and reopen if this is indeed the `sahrani` branch.

**Comment by Vonrichter** [comment]
ah... I check now and i Tell you

**Comment by Vonrichter** [comment]
Ok, bad download from my side.
Moreover i confirm that the issue with ranked vehicles is fixed.

Thank you alot :)

**Comment by Kolmain** [comment]
No problem! Thank you!
